version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  Publish-Site:
    docker:
      - image: cimg/node:18.2.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install --no-install-recommends -y brotli

      - run:
          name: npm install
          command: npm install

      - run:
          name: generate static pages
          command: npm run build

      - run:
          name: install grunt
          command: npm install grunt grunt-cli -g

      - run:
          name: grunt tasks
          command: grunt

      - run:
          name: brotli and gzip compression
          command: bash compress.sh

      - aws-s3/sync:
          arguments: |
            --cache-control "max-age=31536000"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: dist
          to: 's3://static-site-aws-carlo-van'

      - run:
          name: Netlify install
          command: npm install netlify-cli -g

      - run:
          name: Netlify deploy
          command: netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir dist

      - run: npx wrangler pages publish dist --project-name $CLOUDFLARE_PAGES_PROJECT_NAME
workflows:
  Publish-Site-Workflow:
    jobs:
      - Publish-Site
